apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  labels:
    example: remains
spec:
  replicas: 1
  template:
    metadata:
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:plain-text
        ports:
        - containerPort: 80
          name: web
